name: Sugerir uma melhoria
description: Conte o que faria o Ondren mais útil para você.
title: "[Sugestão] "
body:
  - type: textarea
    id: need
    attributes:
      label: O que você gostaria de conseguir fazer?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: Como você imagina essa melhoria?
